language: java
jdk: openjdk7
install:
  - cd ..
  - git clone https://github.com/tolis-e/aerogear-controller-demo.git
  - mvn -f aerogear-controller-demo/pom.xml package
  - cd aerogear-controller-demo-test
  - echo "install begin"
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - echo "install end"
script: mvn test
